MIN_PAGE: int = 1
MIN_PER_PAGE: int = 1
MAX_PER_PAGE: int = 100
MAX_TIMELINE_HOURLY_DAYS: int = 31
MAX_TIMELINE_DAILY_DAYS: int = 366
MIN_TOP_DOMAINS_LIMIT: int = 1
MAX_TOP_DOMAINS_LIMIT: int = 20
DEFAULT_TOP_DOMAINS_LIMIT: int = 5
